# build using the latest maven with amazon corretto jdk image
image: maven:amazoncorretto

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn verify -B
          - mvn clean package -DskipTests -B
          - mvn test -B
        artifacts:
          - target/*.jar