# build using the latest maven with amazon corretto jdk image
image: maven:amazoncorretto

pipelines:
  default:
    - step:
        caches:
          - maven
        script:
          - mvn verify
          - mvn clean package -DskipTests
          - mvn test